#!/bin/bash

: ${ROOTFS:=/depot}

[ -d $ROOTFS ] || mkdir ROOTFS
rpm --root=$ROOTFS --initdb
rpm --root=$ROOTFS -ivh  http://mirror.centos.org/centos/6.6/os/x86_64/Packages/centos-release-6-6.el6.centos.12.2.x86_64.rpm

cp /etc/yum.repos.d/* $ROOTFS/etc/yum.repos.d/
yum install --installroot=$ROOTFS --nogpgcheck -y perl vim

ln -s $ROOTFS/usr/lib64/perl5/CORE/libperl.so $ROOTFS/usr/lib64/libperl.so

source /depot/setpath